runtime: nodejs10
instance_class: F2

# No service keyword to use default service

# To deploy to cloud: gcloud app deploy app.yaml
# how to create yaml for standard environment
# https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/master/appengine/hello-world/standard/app.yaml

# change project: gcloud config set project alex-maths-world